### ISSUE TITLE
Mirror "|" element is taking too much space

### ISSUE THREAD

**Issue by Glandos** [deshiknaves/caret-pos#33]
![image](https://user-images.githubusercontent.com/297578/126791243-47aa4951-19fc-47c9-a18c-3a8db11b669d.png)
 I got the above image by debugging right after `element.parentNode.insertBefore(mirror, element.nextSibling);` in `initializeHTML`, and I add `color: red;` to the mirror element. I also remove the low z-index to show it.

Then we see that after the `|` element, text mirror has an offset. This is not a real issue here, but if the input is narrower, then the mirror is wrapping, and not the original input.
Setting a `max-width` for this element *seems* to work, but I don't want to interfere with existing behavior.

**Comment by Glandos** [comment]
I use the following workaround:
```css
#caret-position-marker {
  /* Workaround https://github.com/deshiknaves/caret-pos/issues/33 */
  display: inline-block !important;
  max-width: 0;
}
```
